### PR TITLE
Rev d

### PR DESCRIPTION
**Pull request by sonyccd**

### CODE REVIEW

**Comment by rjehangir** [comment]
Here's my comments:

- Change R13 to 9K
- Make sure D3 is a schottky diode with minimal forward voltage like 0.3V. This is very important and the symbol is not a schottky right now.
- The pull-up on GPS_EN is technically unnecessary since the ESP will be driving that pin whenever 3.3V is powered.

That's all! Nice job!

**Comment by rjehangir** [comment]
I'm approving, but the revision number and date should be updated.

**Review by rjehangir — DISMISSED** [review]

**Comment by brendanwalters** [comment]
3 questions, but I think the second and third are probably fine.

1) The values for the parts in the MCP73831 reference schematic are ranges, so I'm assuming what we have are @rjehangir suggestions and well-calibrated. But it does suggest the input to VDD and STAT be filtered, and there is no filter anywhere on VCC

2) I think we discussed it last time but I don't remember - the AP2112 example circuit has only 1uF filters on both VIN and VOUT, whereas we have 10uF and 10+0.1uF respectively.

3) The CP2104 wants 1-5uF and 0.1uF filters on REGIN, VIO, VDD; we have a nearby 10 and a more distant 10 and 0.1 (on VCCIO, for which those are the recommended filters for everything else so hopefully that's fine and we don't need to add something just for this one.)


Reviewed the board with particular attention to the bits we moved around Tuesday, looks fine.

**Comment by rjehangir** [comment]
@brendanwalters 

1. The values and design are based off of what is used on the Adafruit board Feather board, which is similar and they should be fine.

2. The larger values should be fine and provide more decoupling support for everything on the board.

3. Again, based on the design and values in the Adafruit Feather board and should be fine!

Thanks for the review!

**Review by brendanwalters — APPROVED** [review]
LGTM then.

**Comment by brendanwalters** [comment]
Although for future reference we should probably use an unambiguous date format, mm-dd-yy is gross

**Comment by brendanwalters** [comment]
We printed a set of these and will be testing shortly - merging for consistency

**Pull request merged**
